services:
  db:
    image: postgres:16
    container_name: aalcDB
    environment:
      POSTGRES_DB: aalcDB
      POSTGRES_USER: sujitbhatta
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - aalc_postgres_data:/var/lib/postgresql/data

volumes:
  aalc_postgres_data: