spring.application.name=server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

server.port=${PORT:8080}

# JWT secret = setting JWT_SECRET env var in production (random password set to default)
###  HS256 requires minimum 32 bytes so, had to have default key cause of WeakKeyException error.
jwt.secret=${JWT_SECRET:c2VjcmV0LWtleS1mb3ItYWFsYy1wcm9qZWN0LWp3dC0yMDI0LXJlcGxhY2UtaW4tcHJvZHVjdGlvbg==}
